'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8745
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _127165653() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("127165653", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1616980_ice_cream_wallpaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1616980-ice-cream-wallpaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _414856() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("414856", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _44_444218_confused_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("44-444218_confused-png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property artisanal_ice_cream() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artisanal+ice+cream", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property artisanal_ice_cream1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artisanal+ice+cream1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Baskin_Robbins_Next_Gen_mural() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baskin-Robbins_Next_Gen_mural", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Baskin_Robbins_Next_Gen_mural1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baskin-Robbins_Next_Gen_mural1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Baskin_Robbins_Next_Gen_mural2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baskin-Robbins_Next_Gen_mural2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property berries_colorful_ice_cream_fruit_wallpaper_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("berries-colorful-ice-cream-fruit-wallpaper-preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property berries_colorful_ice_cream_fruit_wallpaper_preview1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("berries-colorful-ice-cream-fruit-wallpaper-preview1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property berries_raspberry_ice_cream_dessert_wallpaper_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("berries-raspberry-ice-cream-dessert-wallpaper-preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property berries_raspberry_ice_cream_dessert_wallpaper_preview1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("berries-raspberry-ice-cream-dessert-wallpaper-preview1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property budget_16x9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("budget-16x9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property budget_16x91() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("budget-16x91", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cherry_ice_cream_cherries_on_purple_ice_cream_with_cone_wallpaper_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cherry-ice-cream-cherries-on-purple-ice-cream-with-cone-wallpaper-preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Coffee_Ice_Cream_ice_cream_34732931_1024_768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coffee-Ice-Cream-ice-cream-34732931-1024-768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Coffee_Ice_Cream_ice_cream_34732931_1024_7681() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coffee-Ice-Cream-ice-cream-34732931-1024-7681", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property direct_paste_with_content() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("direct-paste-with-content", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enquiry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enquiry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enquiry1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enquiry1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property European_and_American_fashion_brick_wall_ice_cream_shop_food_tooling_wall_specializing_in_the_production() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("European-and-American-fashion-brick-wall-ice-cream-shop-food-tooling-wall-special"& _ 
                        "izing-in-the-production", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frozen_Ribbons_Franchise() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frozen-Ribbons-Franchise", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frozen_Ribbons_Franchise1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frozen-Ribbons-Franchise1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gettyimages_1069685888_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gettyimages-1069685888-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gettyimages_173644640_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gettyimages-173644640-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gettyimages_640948258_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gettyimages-640948258-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gettyimages_936205852_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gettyimages-936205852-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gettyimages_936205852_612x6121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gettyimages-936205852-612x6121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gettyimages_936205852_612x6122() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gettyimages-936205852-612x6122", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gettyimages_944795204_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gettyimages-944795204-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ice_cream_berries_cranberries_raspberries_97837_1920x1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ice_cream_berries_cranberries_raspberries_97837_1920x1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ice_cream_Berry_452879() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ice_cream_Berry_452879", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ice_cream_dishes_2_2015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ice-cream-dishes-2-2015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ice_cream_factory_mulund_west_mulund_west_mumbai_omedw_1200x735() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ice-cream-factory-mulund-west-mulund-west-mumbai-omedw-1200x735", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IceCreamParlour_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IceCreamParlour-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IceCreamParlour_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IceCreamParlour-21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IceCreamParlour_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IceCreamParlour-22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property internet_scifi_marketing_best_landspace_girls_women_anime_movies_cartoon_astract_multicolor_animal_dog_leopard_linux_windows_HD_hight_quality_wallpaper_2979955() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internet scifi marketing best landspace girls women anime movies cartoon astract "& _ 
                        "multicolor animal dog leopard linux windows HD hight quality wallpaper-2979955", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property internet_scifi_marketing_best_landspace_girls_women_anime_movies_cartoon_astract_multicolor_animal_dog_leopard_linux_windows_HD_hight_quality_wallpaper_29799551() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internet scifi marketing best landspace girls women anime movies cartoon astract "& _ 
                        "multicolor animal dog leopard linux windows HD hight quality wallpaper-29799551", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property internet_scifi_marketing_best_landspace_girls_women_anime_movies_cartoon_astract_multicolor_animal_dog_leopard_linux_windows_HD_hight_quality_wallpaper_29799552() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internet scifi marketing best landspace girls women anime movies cartoon astract "& _ 
                        "multicolor animal dog leopard linux windows HD hight quality wallpaper-29799552", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property palsgaard_has_ice_cream_application_centres_around_the_world() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("palsgaard-has-ice-cream-application-centres-around-the-world", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property palsgaard_has_ice_cream_application_centres_around_the_world1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("palsgaard-has-ice-cream-application-centres-around-the-world1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property palsgaard_has_ice_cream_application_centres_around_the_world2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("palsgaard-has-ice-cream-application-centres-around-the-world2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ricevimento_stoccaggio_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ricevimento-stoccaggio-8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ricevimento_stoccaggio_8__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ricevimento-stoccaggio-8 (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ricevimento_stoccaggio_8__2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ricevimento-stoccaggio-8 (2)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rush_Inn_Avon_Creamery_ice_cream() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rush-Inn-Avon-Creamery-ice-cream", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property screen_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screen-0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Screenshot__41_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot (41)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Strawberry_ice_cream_pink_1920x1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Strawberry-ice-cream-pink_1920x1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
